//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace catChaReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Catcharacter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_Catcharacter()
        {
            this.Shop_CatStatus = new HashSet<Shop_CatStatus>();
        }
    
        public int CatPersonalityID { get; set; }
        public string Personality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_CatStatus> Shop_CatStatus { get; set; }
    }
}
